from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(Estado)
admin.site.register(Municipio)
admin.site.register(Ocupacion)
admin.site.register(Parentesco)
admin.site.register(EstadoCivil)
admin.site.register(Escolaridad)
admin.site.register(Referidopor)
admin.site.register(ServicioCree)
admin.site.register(ProgramaCree)
admin.site.register(TipoVivienda)
admin.site.register(MotivoEstudioSE)
admin.site.register(IngresosEgresos)
admin.site.register(SeguridadSocial)
admin.site.register(TenenciaVivienda)
admin.site.register(ServicioVivienda)
admin.site.register(ComponenteVivienda)
admin.site.register(ConstruccionVivienda)
admin.site.register(ClasificacionEconomica)
admin.site.register(ConsecutivoExpendiente)
admin.site.register(MensajesEnfemeriaTicket)
admin.site.register(MensajesCartaConsentimiento)
admin.site.register(BarreraArquitectonicaVivienda)